const countryList = [
  {name: 'Vatican City', code: 'VA'},
  {name: 'Ethiopia', code: 'ET'},
  {name: 'Montenegro', code: 'ME'},
  {name: 'Namibia', code: 'NA'},
  {name: 'Ghana', code: 'GH'},
  {name: 'San Marino', code: 'SM'},
  {name: 'Niger', code: 'NE'},
  {name: 'Malta', code: 'MT'},
  {name: 'Kazakhstan', code: 'KZ'},
  {name: 'Kenya', code: 'KE'},
  {name: 'Monaco', code: 'MC'},
  {name: 'Angola', code: 'AO'},
  {name: 'Bhutan', code: 'BT'},
  {name: 'Mali', code: 'ML'},
  {name: 'Rwanda', code: 'RW'},
  {name: 'Belize', code: 'BZ'},
  {name: 'São Tomé and Príncipe', code: 'ST'},
  {name: 'Cuba', code: 'CU'},
  {name: 'Nigeria', code: 'NG'},
  {name: 'Uganda', code: 'UG'},
  {name: 'Liechtenstein', code: 'LI'},
  {name: 'Bosnia and Herzegovina', code: 'BA'},
  {name: 'Senegal', code: 'SN'},
  {name: 'Andorra', code: 'AD'},
  {name: 'Seychelles', code: 'SC'},
  {name: 'Azerbaijan', code: 'AZ'},
  {name: 'Albania', code: 'AL'},
  {name: 'Macedonia', code: 'MK'},
  {name: 'Croatia', code: 'HR'},
  {name: 'Cyprus', code: 'CY'},
  {name: 'Bangladesh', code: 'BD'},
  {name: 'Japan', code: 'JP'},
  {name: 'Canada', code: 'CA'},
  {name: 'Sudan', code: 'SD'},
  {name: 'Georgia', code: 'GE'},
  {name: 'Sierra Leone', code: 'SL'},
  {name: 'Somalia', code: 'SO'},
  {name: 'South Africa', code: 'ZA'},
  {name: 'Nicaragua', code: 'NI'},
  {name: 'Jordan', code: 'JO'},
  {name: 'Swaziland', code: 'SZ'},
  {name: 'Kuwait', code: 'KW'},
  {name: 'Laos', code: 'LA'},
  {name: 'Kyrgyzstan', code: 'KG'},
  {name: 'Norway', code: 'NO'},
  {name: 'Hungary', code: 'HU'},
  {name: 'Ireland', code: 'IE'},
  {name: 'Algeria', code: 'DZ'},
  {name: 'Spain', code: 'ES'},
  {name: 'Costa Rica', code: 'CR'},
  {name: 'Brunei', code: 'BN'},
  {name: 'Barbados', code: 'BB'},
  {name: 'Yemen', code: 'YE'},
  {name: 'Central African Republic', code: 'CF'},
  {name: 'Philippines', code: 'PH'},
  {name: 'Israel', code: 'IL'},
  {name: 'Belgium', code: 'BE'},
  {name: 'Panama', code: 'PA'},
  {name: 'United States of America', code: 'US'},
  {name: 'Tanzania', code: 'TZ'},
  {name: 'Finland', code: 'FI'},
  {name: 'Luxembourg', code: 'LU'},
  {name: 'Denmark', code: 'DK'},
  {name: 'Sweden', code: 'SE'},
  {name: 'Lithuania', code: 'LT'},
  {name: 'Poland', code: 'PL'},
  {name: 'Switzerland', code: 'CH'},
  {name: 'Italy', code: 'IT'},
  {name: 'Indonesia', code: 'ID'},
  {name: 'Kiribati', code: 'KI'},
  {name: 'Russia', code: 'RU'},
  {name: 'Fiji', code: 'FJ'},
  {name: 'Malaysia', code: 'MY'},
  {name: 'Zimbabwe', code: 'ZW'},
  {name: 'Mongolia', code: 'MN'},
  {name: 'Zambia', code: 'ZM'},
  {name: 'Bahrain', code: 'BH'},
  {name: 'Brazil', code: 'BR'},
  {name: 'Armenia', code: 'AM'},
  {name: 'Venezuela', code: 'VE'},
  {name: 'Austria', code: 'AT'},
  {name: 'Nepal', code: 'NP'},
  {name: 'South Sudan', code: 'SS'},
  {name: 'Greece', code: 'GR'},
  {name: 'Myanmar', code: 'MM'},
  {name: 'Turkey', code: 'TR'},
  {name: 'Portugal', code: 'PT'},
  {name: `People's Republic of China`, code: 'CN'},
  {name: 'Lebanon', code: 'LB'},
  {name: 'United Kingdom', code: 'GB'},
  {name: 'Uzbekistan', code: 'UZ'},
  {name: 'Tunisia', code: 'TN'},
  {name: 'Marshall Islands', code: 'MH'},
  {name: 'Togo', code: 'TG'},
  {name: 'Federated States of Micronesia', code: 'FM'},
  {name: 'Maldives', code: 'MV'},
  {name: 'Netherlands', code: 'NL'},
  {name: 'Ivory Coast', code: 'CI'},
  {name: 'Cameroon', code: 'CM'},
  {name: 'The Gambia', code: 'GM'},
  {name: 'Guinea', code: 'GN'},
  {name: 'Guinea-Bissau', code: 'GW'},
  {name: 'Gabon', code: 'GA'},
  {name: 'Democratic Republic of the Congo', code: 'CD'},
  {name: 'Guyana', code: 'GY'},
  {name: 'Paraguay', code: 'PY'},
  {name: 'Sri Lanka', code: 'LK'},
  {name: 'Comoros', code: 'KM'},
  {name: 'Chile', code: 'CL'},
  {name: 'Suriname', code: 'SR'},
  {name: 'Saudi Arabia', code: 'SA'},
  {name: 'Republic of the Congo', code: 'CG'},
  {name: 'Colombia', code: 'CO'},
  {name: 'Ecuador', code: 'EC'},
  {name: 'Djibouti', code: 'DJ'},
  {name: 'Syria', code: 'SY'},
  {name: 'Madagascar', code: 'MG'},
  {name: 'Belarus', code: 'BY'},
  {name: 'Libya', code: 'LY'},
  {name: 'Cape Verde', code: 'CV'},
  {name: 'Germany', code: 'DE'},
  {name: 'Lesotho', code: 'LS'},
  {name: 'Liberia', code: 'LR'},
  {name: 'Oman', code: 'OM'},
  {name: 'Botswana', code: 'BW'},
  {name: 'Benin', code: 'BJ'},
  {name: 'Malawi', code: 'MW'},
  {name: 'Burkina Faso', code: 'BF'},
  {name: 'Pakistan', code: 'PK'},
  {name: 'Qatar', code: 'QA'},
  {name: 'Burundi', code: 'BI'},
  {name: 'Uruguay', code: 'UY'},
  {name: 'Egypt', code: 'EG'},
  {name: 'Mauritius', code: 'MU'},
  {name: 'Morocco', code: 'MA'},
  {name: 'Mozambique', code: 'MZ'},
  {name: 'Mauritania', code: 'MR'},
  {name: 'Trinidad and Tobago', code: 'TT'},
  {name: 'Turkmenistan', code: 'TM'},
  {name: 'Bolivia', code: 'BO'},
  {name: 'Saint Vincent and the Grenadines', code: 'VC'},
  {name: 'United Arab Emirates', code: 'AE'},
  {name: 'Tajikistan', code: 'TJ'},
  {name: 'Taiwan', code: 'TW'},
  {name: 'Eritrea', code: 'ER'},
  {name: 'Iceland', code: 'IS'},
  {name: 'Equatorial Guinea', code: 'GQ'},
  {name: 'Mexico', code: 'MX'},
  {name: 'Thailand', code: 'TH'},
  {name: 'Estonia', code: 'EE'},
  {name: 'Chad', code: 'TD'},
  {name: 'Bahamas', code: 'BS'},
  {name: 'Argentina', code: 'AR'},
  {name: 'Guatemala', code: 'GT'},
  {name: 'Peru', code: 'PE'},
  {name: 'Antigua and Barbuda', code: 'AG'},
  {name: 'Serbia', code: 'RS'},
  {name: 'Jamaica', code: 'JM'},
  {name: 'Saint Lucia', code: 'LC'},
  {name: 'Vietnam', code: 'VN'},
  {name: 'Saint Kitts and Nevis', code: 'KN'},
  {name: 'South Korea', code: 'KR'},
  {name: 'Grenada', code: 'GD'},
  {name: 'Afghanistan', code: 'AF'},
  {name: 'Australia', code: 'AU'},
  {name: 'Tonga', code: 'TO'},
  {name: 'Iran', code: 'IR'},
  {name: 'Tuvalu', code: 'TV'},
  {name: 'Iraq', code: 'IQ'},
  {name: 'Cook Islands', code: 'CK'},
  {name: 'Cambodia', code: 'KH'},
  {name: 'North Korea', code: 'KP'},
  {name: 'India', code: 'IN'},
  {name: 'Niue', code: 'NU'},
  {name: 'Honduras', code: 'HN'},
  {name: 'New Zealand', code: 'NZ'},
  {name: 'Jersey', code: 'JE'},
  {name: 'Dominica', code: 'DM'},
  {name: 'Dominican Republic', code: 'DO'},
  {name: 'Haiti', code: 'HT'},
  {name: 'El Salvador', code: 'SV'},
  {name: 'Slovenia', code: 'SI'},
  {name: 'Slovakia', code: 'SK'},
  {name: 'Moldova', code: 'MD'},
  {name: 'Latvia', code: 'LV'},
  {name: 'East Timor', code: 'TL'},
  {name: 'Palau', code: 'PW'},
  {name: 'Czech Republic', code: 'CZ'},
  {name: 'Singapore', code: 'SG'},
  {name: 'Nauru', code: 'NR'},
  {name: 'Ukraine', code: 'UA'},
  {name: 'Bulgaria', code: 'BG'},
  {name: 'Romania', code: 'RO'},
  {name: 'Samoa', code: 'WS'},
  {name: 'Vanuatu', code: 'VU'},
  {name: 'Solomon Islands', code: 'SB'},
  {name: 'Papua New Guinea', code: 'PG'},
  {name: 'France', code: 'FR'}
  ]